### PR TITLE
limit cmnds to md files only

### PR DESCRIPTION
**Pull request by ctf0**

### CODE REVIEW

**Comment by mdickin** [comment]
Were you running into an issue somewhere? The keybindings in this extension are already limited to certain files. That's handled by the `markdownShortcuts:enabled` flag in the lines you edited.

**Comment by ctf0** [comment]
the title icons were showing everywhere

**Comment by mdickin** [comment]
Can you provide a screenshot? I don't see this happening. If I open a new file and change the file type to Markdown, then the icons appear. If I change it to something else, then they disappear.

Have you modified the `markdownShortcuts.languages` preference?

**Comment by ctf0** [comment]
oh thats why then, i made changes to `markdownShortcuts.languages`, thanx for ur quick reply 👍

**Pull request closed without merging**
