### PR TITLE
Added tests and fixed code block for collapsed selection bug

### LINKED ISSUE #15: Toggle block doesnt work for a collapsed selection
1. Open a new markdown file.
1. Set contents to the following (where `^` marks a collapsed range position):
  ```markdown
  # foo

  ba^r
  ```
1. Press `ctrl+m, ctrl+c` to insert a code block.

Code block gets inserted.

Nothing happens, extension throws na exception.

> Running the contributed command:'md-shortcut.toggleCodeBlock' failed.

### PR DESCRIPTION
**Pull request by mlewand**
I was thinking about tackling #5, however I any new code to be covered with unit tests ❤️.

Since some time ago I created a pretty neat module [vscode-test-content](https://www.npmjs.com/package/vscode-test-content) for simple content asserting, which is a brilliant match for your extension, I decided to contribute tests.

As a result this PR not only adds the test but also fixes #15 - which I was able to tell only after the tests were done.

I intentionally left multiple commits in history, so you have a clear history and can see the whole process to adapt it on your own.

Cheers!

### CODE REVIEW

**Comment by mdickin** [comment]
This looks fantastic! As a TDD proponent, I've always felt guilty that I never got any tests set up for this project. that vscode-test-content library looks pretty great!

Unfortunately, the "Block code Toggles with ranged selection" (which I believe tests #15 ) is failing.

image

I'm looking into it now.

**Comment by mlewand** [comment]
@mdickin Is it failing on master branch? Since it's merged I'll have a look at it.

**Comment by mlewand** [comment]
Weird, tests are all green for me at d4f3a78

**Comment by mdickin** [comment]
I don't see where it would make a difference here, but are you using a Mac or *nix machine? I'm on Windows. I know sometimes newlines get weird.

**Comment by mlewand** [comment]
I'm also sitting on Windows machine.

**Comment by mlewand** [comment]
Maybe some untracked changes? Does `git status --short` sit silent?

**Comment by mdickin** [comment]
Nope, no untracked changes.

**Comment by mdickin** [comment]
If you test it through the extension, does it work correctly?

**Comment by mlewand** [comment]
@mdickin yup it does, it toggles the block comment well. Does it for you?

**Comment by mlewand** [comment]
I have an idea, it might be a matter of vscode version in deps, I'm on it.

**Comment by mdickin** [comment]
No, it wasn't working in the extension, it was doubling the code block. Set a breakpoint in `isSelectionMatch` and saw that the selection has `\r\n` at the end, rather than just `\n`.

**Comment by mlewand** [comment]
Checked on CI, it works for me on one setup, and fails on the other.

Works on Travis: https://travis-ci.org/mlewand/vscode-markdown-shortcuts/jobs/214487846

Fails on Appveyor https://ci.appveyor.com/project/mlewand/vscode-markdown-shortcuts/build/1.0.2/job/5ld33rfl5ryt6eor

**Comment by mlewand** [comment]
Line ending might be the case here. On my local settings I have `\n` line feed enforced, Appveyor uses `\r\n` as far as I'm concerned.

**Comment by mdickin** [comment]
Hmm, any idea how to determine which line ending to use?

**Comment by mlewand** [comment]
Let me check, I was  dealing with it in one of my plugins...

**Comment by mlewand** [comment]
There's a nice method to *set* EOLs for the document [TextEditorEdit#setEndOfLine](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nametexteditoreditaspan-classcodeitem-id339texteditoreditspan)

**Comment by mdickin** [comment]
Found it!

```javascript
var newLine = vscode.workspace.getConfiguration('files').get('eol', '\r\n');
```

**Comment by mlewand** [comment]
It's rather tricky I'd say, isn't it? All right, I need to leave you as it's 2:30AM here, and I need to get some sleep after night of open sourcing :P Hope you'll be able to simply fix it, if not I can give a hand tomorrow, feel free to reach me out at [@m_lewand](https://twitter.com/m_lewand).

**Comment by mdickin** [comment]
Haha, you deserve some rest. Thanks a ton!

**Pull request merged**
